AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
